service: lambda-jwk-manager

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}
    AUTH0_CLIENT_ID: ${env:AUTH0_CLIENT_ID}
    AUTH0_CLIENT_SECRET: ${env:AUTH0_CLIENT_SECRET}

plugins:
  - serverless-dotenv-plugin

functions:
  linkCredential:
    handler: index.handler
    events:
      - http:
          path: link-credential
          method: post
