service: lambda-jwk-manager

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  environment:
    AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}
    AUTH0_CLIENT_ID: ${env:AUTH0_CLIENT_ID}
    AUTH0_CLIENT_SECRET_SECRET_NAME: ${env:AUTH0_CLIENT_SECRET_NAME}
    JWK_METADATA_KEY: ${env:JWK_METADATA_KEY}
    EXPIRY_METADATA_KEY: ${env:EXPIRY_METADATA_KEY}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:${env:AUTH0_CLIENT_SECRET_NAME}-*

plugins:
  - serverless-dotenv-plugin

functions:
  jwkManager:
    handler: index.handler
    events:
      - http:
          path: jwk-manager
          method: post
